### PR TITLE
Implement marking levels as re-uploads

### PR DESCRIPTION
**Pull request by turecross321**
image
image
image
image

### CODE REVIEW

**Comment by jvyden** [comment]
What does it look like with a null publisher, but with an original publisher? This will be a common case in the future.

**Comment by turecross321** [comment]
image
image

**Comment by jvyden** [comment]
sick

**Comment by turecross321** [comment]
We might want to add the ability to get all levels by the `originalPublisher`, but we can do that later

**Review by jvyden — APPROVED** [review]

**Pull request merged**
